<?php

// de lang variables

$text['Add new record'] = 'Neuer Datensatz';
$text['Add new %s'] = 'Neuer Datensatz: %s';
$text['all_records'] = 'Alle Datens&auml;tze';
$text['prev_20_records'] = 'Vorige 20 Datens&auml;tze';
$text['next_20_records'] = 'N&auml;chste 20 Datens&auml;tze';
$text['record_was_inserted'] = 'Datensatz wurde eingef&uuml;gt';
$text['warning'] = 'Warnung';
$text['action'] = 'Aktion';
$text['none_selected'] = 'Nichts ausgew&auml;hlt';
$text['edit'] = 'Bearbeiten';
$text['delete'] = 'L&ouml;schen';
$text['show'] = 'Anzeigen';
$text['back-to-overview'] = 'Zur&uuml;ck zur &Uuml;bersicht';
$text['no_selection_possible'] = 'Keine Auswahl m&ouml;glich.';
$text['calculated_field'] = 'berechnetes Feld';
$text['will_be_added_automatically'] = 'wird automatisch hinzugef&uuml;gt';
$text['no_selection'] = 'Keine Auswahl';
$text['record_was_updated'] = 'Datensatz wurde aktualisiert';
$text['record_was_deleted'] = 'Datensatz wurde gel&ouml;scht';
$text['reason'] = 'Grund';
$text['following_values_checked_again'] = 'Die folgenden Werte m&uuml;ssen &uuml;berpr&uuml;ft werden';
$text['database'] = 'Datenbank';
$text['no_image'] = 'Kein Bild';
$text['sql-query'] = 'SQL-Abfrage';
$text['database-error'] = 'Datenbankfehler';
$text['decimal'] = 'dezimal';
$text['no_source_defined'] = 'Keine Quelle angegeben';
$text['image_not_display'] = 'Bild kann (noch) nicht angezeigt werden';
$text['update'] = 'Aktualisieren';
$text['update_to'] = 'Aktualisieren der';
$text['delete_from'] = 'L&ouml;schen aus der';
$text['add_to'] = 'Hinzuf&uuml;gen zur';
$text['error-sql-incorrect'] = 'Ein Fehler ist in einer Datenbankabfrage aufgetreten.';
$text['add'] = 'Hinzuf&uuml;gen';
$text['a_record'] = 'eines Datensatzes';
$text['failed'] = 'fehlgeschlagen';
$text['insert'] = 'Einf&uuml;gen';
$text['order by'] = 'Sortiere nach';
$text['asc'] = 'aufsteigend';
$text['desc'] = 'absteigend';
$text['new'] = 'Neu';
$text['no-data-available'] = 'Keine Daten vorhanden';
$text['edit-after-save'] = 'Kein Eintrag m&ouml;glich. Bitte speichern Sie zuerst den Datensatz.';
$text['table-empty'] = 'Keine Eintr&auml;ge vorhanden';
$text['detail'] = 'Details';
$text['Value_incorrect_in_field'] = 'Wert ist falsch im Feld:';
$text['Value missing in field'] = 'Wert fehlt im Feld:';
$text['Following_errors_occured'] = 'Die folgenden Fehler sind aufgetreten';
$text['This record could not be deleted because there are details about this record in other records.'] = 'Dieser Datensatz konnte nicht gel&ouml;scht werden, da es Details zu diesem Datensatz in anderen Datens&auml;tzen gibt.';
$text['Detail records exist in the following tables:'] = 'Detaildatens&auml;tze existieren in den folgenden Tabellen:';
$text['No relation table'] = 'Keine Tabelle %s. Das Programm funktioniert nicht ohne.';
$text['No records in relation table'] = 'Keine Eintr&auml;ge in der Tabelle %s. Bitte f&uuml;llen Sie diese Tabelle mit Werten.';
$text['show_record'] = 'Datensatz anzeigen';
$text['Database error. This query has ambiguous values in ID field.'] = 'Datenbankfehler. Diese Abfrage hat kein eindeutiges ID-Feld.';
$text['search'] = 'suche';
$text['Search'] = 'Suche';
$text['in'] = 'in';
$text['all fields'] = 'allen Feldern';
$text['review'] = 'Anzeigen';
$text['hidden'] = 'versteckt';
$text['dec'] = 'dez';
$text['Cancel'] = 'Abbrechen';
$text['Please enter more characters.'] = 'Bitte geben Sie mehr Buchstaben ein.';
$text['records'] = 'Datens&auml;tze';
$text['records total'] = 'Datens&auml;tze gesamt';
$text['record total'] = 'Datensatz gesamt';
$text['No entry found. Try less characters.'] = 'Keinen Eintrag gefunden. Versuchen Sie es mit weniger Zeichen.';
$text['all'] = 'Alle';
$text['N'] = '<abbr title="Nord">N</abbr>';
$text['E'] = '<abbr title="Ost">O</abbr>';
$text['S'] = '<abbr title="Süd">S</abbr>';
$text['W'] = '<abbr title="West">W</abbr>';
$text['. Correct values are: '] = '. Korrekte Werte: ';
$text['is not a correct value for'] = 'ist als Eingabe nicht korrekt f&uuml;r';
$text['sec'] = 'Sekunden';
$text['deg'] = 'Grad';
$text['min'] = 'Minuten';
$text['hemisphere'] = 'Hemisph&auml;re';
$text['N/A'] = '<abbr title="keine Angabe">k.&nbsp;A.</abbr>';
$text['Nothing'] = 'Nichts';
$text['Old:'] = 'Alt:';
$text['New:'] = 'Neu:';
$text['(Please confirm your new password twice)'] = '(Bitte best&auml;tigen Sie Ihr Passwort zweimal)';
$text['Your password has been changed!'] = 'Ihr Passwort wurde ge&auml;ndert.';
$text['Your current password is different from what you entered. Please try again.'] = 'Ihr aktuelles Passwort ist nicht das, was Sie eingegeben haben. Bitte versuchen Sie es nocheinmal.';
$text['New passwords do not match. Please try again.'] = 'Die Eingaben f&uuml;r das neue Passwort unterscheiden sich. Bitte versuchen Sie es nocheinmal.';
$text['Please enter your current password and twice your new password.'] = 'Bitte geben Sie Ihr aktuelles Passwort und zweimal das neue Passwort ein.';
$text['Error: '] = 'Fehler: ';
$text['No file was uploaded.'] = 'Es wurde keine Datei hochgeladen.';
$text['File was only partially uploaded.'] = 'Die Datei wurde nur teilweise hochgeladen.';
$text['File is too big.'] = 'Die Datei ist zu gro&szlig;.';
$text['Maximum allowed filesize is'] = 'Maximal erlaubte Dateigr&ouml;&szlig;e:';
$text['Minimum width %s was not reached.'] = 'Minimale Breite %s nicht eingehalten.';
$text['Minimum height %s was not reached.'] = 'Minimale H&ouml;he %s nicht eingehalten.';
$text['Maximum width %s has been exceeded.'] = 'Maximale Breite %s wurde &uuml;berschritten.';
$text['Maximum height %s has been exceeded.'] = 'Maximale H&ouml;he %s wurde &uuml;berschritten.';
$text['Unsupported filetype:'] = 'Nicht unterst&uuml;tzter Dateityp:';
$text['Supported filetypes are:'] = 'Diese Dateitypen werden unterst&uuml;tzt:';
$text['Could not delete %s.'] = 'Konnte %s nicht l&ouml;schen.';
$text['Could not delete %s, file did not exist.'] = 'Konnte %s nicht l&ouml;schen, da die Datei nicht existierte.';
$text['File: '] = 'Datei: ';
$text['There is no record under this ID:'] = 'Es existiert kein Datensatz unter dieser ID:';
$text['Rules for secure passwords'] = 'Regeln f&uuml;r sichere Pa&szlig;w&ouml;rter';
$text['password-rules'] = 'Pa&szlig;w&ouml;rter sollten aus mindestens acht Zeichen bestehen. Dabei sollten Gro&szlig;- und Kleinbuchstaben, Ziffern und Sonderzeichen (?=+; etc.) enthalten sein. Damit man ein Pa&szlig;wort sich auch merken kann, sind Eselsbr&uuml;cken hilfreich.

Beispiele f&uuml;r gute Pa&szlig;w&ouml;rter:

* !1Pw=ig! (Merkregel: !Ein Passwort ist immer geheim!)
* 1sPh&uuml;o&auml;o&Ouml;  (Merkregel: ein starkes Passwort hat &uuml; oder &auml; oder &ouml;)
* 17Nbg03h (Merkregel: Ich telefoniere nicht besonders gern oder besonders h&auml;ufig, Buchstaben teilweise durch &auml;hnlich aussehende Zahlen ersetzt)'; 
$text['New and old password are identical. Please choose a different new password.'] = 'Neues und altes Passwort sind identisch. Bitte w&auml;hlen Sie ein anderes, neues Passwort aus.';
$text['selection:'] = 'Auswahl:';
$text['Export'] = 'Export';
$text['Duplicate entry'] = 'Doppelter Eintrag in dieser Tabelle. Bitte &uuml;berpr&uuml;fen Sie, ob entweder der gew&uuml;nschte Datensatz bereits existiert oder ob Sie Ihren Eintrag &auml;ndern k&ouml;nnen.';
$text['Detail record could not be handled'] = 'Teildatensatz konnte nicht gespeichert werden.';
$text['Error during database operation'] = 'Fehler bei Datenbankzugriff';
$text['The following error(s) occured in project %s:'] = 'Folgende(r) Fehler sind im Projekt %s aufgetaucht:';
$text['- unknown -'] = '- unbekannt -';
$text['Add %s'] = '%s hinzuf&uuml;gen';
$text['Remove %s'] = '%s entfernen';
$text['Delete this file'] = 'Diese Datei l&ouml;schen';
$text['Show all records'] = 'Zeige alle Datens&auml;tze (ohne Suchfilter)';
$text['Warning!'] = 'Achtung!';
$text['Critical Error!'] = 'Fehler!';
$text['File could not be saved. There is a problem with the user rights. We are working on it.'] = 'Die Datei konnte nicht gespeichert werden. Es gibt ein Problem, aber wir arbeiten daran.';
$text['We are working on the solution of this problem. Sorry for your inconvenience.'] = 'Wir arbeiten an der L&ouml;sung dieses Problems. Bitte entschuldigen Sie die Unannehmlichkeiten.';
$text['An error occured. We are working on the solution of this problem. Sorry for your inconvenience. Please try again later.'] = 'Ein Fehler ist aufgetreten. Wir arbeiten an der L&ouml;sung des Problems. Bitte entschuldigen Sie die Unannehmlichkeiten. Versuchen Sie es bitte sp&auml;ter nocheinmal.';
$text['File could not be imported.'] = 'Datei konnte nicht importiert werden.';
$text['Folder could not be imported.'] = 'Verzeichnis konnte nicht importiert werden.';
$text['Import was successful.'] = 'Import war erfolgreich.';
$text['Folder OK'] = 'Verzeichnis OK';
$text['Folder "%s" does not exist.'] = 'Das Verzeichnis "%s" existiert nicht.';
$text['Warning! Insufficient access rights. Please make sure, that the source directory is writeable.'] = 'Warnung! Die Zugriffsrechte reichen nicht aus. Bitte stellen Sie sicher, dass das Quellverzeichnis schreibbar ist.';
$text['%s files left for import. Please wait, the script will reload itself.'] = '%s Dateien m&uuml;ssen noch importiert werden. Bitte warten Sie, das Skript ruft sich erneut auf.';
$text['Field name'] = 'Feldname';
$text['incorrect value'] = 'falscher Wert';
$text['Selection'] = 'Auswahl';
$text['Import data'] = 'Import Daten';
$text['String <em>"%s"</em> is not allowed'] = 'Die Zeichenfolge <em>"%s"</em> ist nicht erlaubt';
?>