<?php 

/*

zzform

This script (c) Copyright 2004-2009 Gustaf Mossakowski, gustaf@koenige.org
No use without permission. The use of this product is restricted
to what has been agreed on in written or spoken form beforehands. If nothing 
has been explicitly said about the use, these scripts may not be used for a
different database than originally intended.

required: at least PHP 4.1.2 
lower PHP versions have not been tested
- mysql_real_escape_string: above 4.3 (addslashes will be used in PHP versions prior)
- exif_read_info: above 4.2 (no exif data will be read in PHP versions prior)


List of functions in this file

	zzform_all				(optional call, if page['head'] and ['foot'] shall
							be incorporated)

		zzform				main zzform function

			zz_initialize		sets defaults, imports modules, reads URI
			microtime_float		microtimer, for debugging

	zzform_multi			multi edit for zzform, e. g. import

*/

//	Required Variables, global so they can be used by the including script after
//	processing as well

global $zz;			// Table description
global $zz_conf;	// Config variables
global $zz_saved;	// saved config variables
global $zz_tab;		// Table values, generated by zzform()
global $zz_page;	// Page (Layout) variables


function zzform() {
	global $zz_timer;
	global $zz_debug;
	$zz_timer = microtime_float();	// for debug only
	$zz_debug = array();

	global $zz;			// Table description
	global $zz_conf;	// Config variables
	global $zz_saved;	// saved config variables
	global $zz_tab;		// Table values, generated by zzform()
	global $zz_page;	// Page (Layout) variables

	$zzform = true; // This variable signals that zz_form is included
	if (empty($zz_conf['zzform_calls'])) $zz_conf['zzform_calls'] = 1;
	else $zz_conf['zzform_calls']++;

//	Variables which are required by several functions
	global $zz_error;
	global $text;
	global $zzform;

//
//	Default Configuration
//

//	initialize variables
	$zz_error = array();
	$zz_error['error'] = false;	// if true, exit script immediately
	$upload_form = false;
	$zz['result'] = false;
	$zz['headers'] = false;
	$zz['output'] = false;
	$zz_var = array();
	$zz_allowed_params = array();
	$zz_tab = array();

	if ($zz_conf['zzform_calls'] == 1) {
		// set default configuration variables
		// import modules
		// set and get URI
		zz_initialize($zz_allowed_params, $zz_var);
		if ($zz_error['error']) return zz_error(); // exits script
		if ($zz_conf['multi']) {
			// save variables for later use
			$zz_saved['conf'] = $zz_conf;
			$zz_saved['var'] = $zz_var;
			$zz_saved['allowed_params'] = $zz_allowed_params;
		}
	} elseif (empty($zz_conf['multi'])) { // show a warning only if zzform is not explicitly called via zzform_multi()
		$zz_error[] = array(
			'msg_dev' => 'zzform has been called as a function more than once. You might want to check if this is correct.',
			'level' => E_USER_NOTICE
		);
		$zz['output'] .= zz_error();
	} else {	// it's called via zzform_multi and not for the first time
		// use initial settings
		$zz_var = $zz_saved['var'];
		$zz_allowed_params = $zz_saved['allowed_params'];
	}

	if ($zz_conf['modules']['debug']) {
		$zz_debug_time_this_function = microtime_float();
		zz_debug(__FUNCTION__, $zz_debug_time_this_function, "variables");
	}

//
//	Database connection, set db_name
//

	// get current db to SELECT it again before exitting
	$result = mysql_query('SELECT DATABASE()');
	$zz_conf['db_current'] = $result ? mysql_result($result, 0, 0) : '';
	// main database normally is the same db that zzform() uses for its
	// operations, but if you use several databases, this is the one which
	// is the main db, i. e. the one that will be used if no other database
	// name is specified
	$zz_conf['db_main'] = false;

	if (!isset($zz_conf['db_connection'])) include_once $zz_conf['dir_custom'].'/db.inc.php';
	// get db_name.
	// 1. best way: put it in zz_conf['db_name']
	if (!empty($zz_conf['db_name'])) {
		$dbname = mysql_select_db($zz_conf['db_name']);
		if (!$dbname) {
			$zz_error[] = array(
				'mysql' => mysql_error(),
				'query' => 'SELECT DATABASE("'.$zz_conf['db_name'].'")',
				'level' => E_USER_ERROR
			);
			return zz_error(); // exits script
		}
		$zz_tab[0]['db_name'] = $zz_conf['db_name'];
	// 2. alternative: use current database
	} else {
		$result = mysql_query('SELECT DATABASE()');
		if (mysql_error()) {
			$zz_error[] = array(
				'mysql' => mysql_error(),
				'query' => 'SELECT DATABASE()',
				'level' => E_USER_ERROR
			);
			return zz_error(); // exits script
		}
		$zz_conf['db_name'] = mysql_result($result, 0, 0);
		$zz_tab[0]['db_name'] = $zz_conf['db_name'];
	}

	// 3. alternative plus foreign db: put it in zz['table']
	if (preg_match('~(.+)\.(.+)~', $zz['table'], $db_name)) { // db_name is already in zz['table']
		if ($zz_conf['db_name'] AND $zz_conf['db_name'] != $db_name[1]) {
			// this database is different from main database, so save it here
			// for later
			$zz_conf['db_main'] = $zz_conf['db_name'];
		} elseif (!$zz_conf['db_name']) { 
			// no database selected, get one, quick!
			$dbname = mysql_select_db($db_name[1]);
			if (!$dbname) {
				$zz_error[] = array(
					'mysql' => mysql_error(),
					'query' => 'SELECT DATABASE("'.$db_name[1].'")',
					'level' => E_USER_ERROR
				);
				return zz_error(); // exits script
			}
		}
		$zz_conf['db_name'] = $db_name[1];
		$zz_tab[0]['db_name'] = $db_name[1];
		$zz['table'] = $db_name[2];
	}

	if (empty($zz_conf['db_name'])) {
		$zz_error[] = array(
			'msg_dev' => 'Please set the variable <code>$zz_conf[\'db_name\']</code>. It has to be set to the main database name used for zzform.',
			'level' => E_USER_ERROR
		);
		return zz_error(); // exits script
	}

//
//	Filter
//

	if (!empty($zz_conf['filter'])) {
		// initialize filter, set defaults
		foreach ($zz_conf['filter'] AS $filter) {
			if (empty($filter['identifier'])) $filter['identifier'] = urlencode($filter['title']);
			// set default filter, default default filter is 'all'
			if (!empty($filter['default_selection']) AND !isset($_GET['filter'][$filter['identifier']])) {
				$_GET['filter'][$filter['identifier']] = $filter['default_selection'];
			}
		}
		// set filter for complete form
		if (!empty($_GET['filter'])) {
			foreach ($zz_conf['filter'] AS $filter) {
				if (in_array($filter['identifier'], array_keys($_GET['filter']))
					AND in_array($_GET['filter'][$filter['identifier']], array_keys($filter['selection']))
					AND $filter['type'] == 'show_hierarchy') {
				// it's a valid filter, so apply it.
					$zz_conf['show_hierarchy'] = $_GET['filter'][$filter['identifier']];
				}
			}
		}
	}

//
// Initialize variables
//

	// initialize ID value
	$zz_tab[0][0]['id']['value'] = false;

	//	initialize WHERE
	// Add with suggested values
	$zz_var['where'] = false;
	$where_with_unique_id = false;
	$where_condition = array();
	if (!empty($_GET['where'])) {
		$where_condition = $_GET['where'];
	}
	// add will overwrite write_once with values, in case there are identical fields
	if (!empty($_GET['add'])) {
		$where_condition = array_merge($where_condition, $_GET['add']);
		foreach ($_GET['add'] as $key => $value) {
			$zz_var['zz_fields'][$key]['value'] = $value;
			$zz_var['zz_fields'][$key]['type'] = 'hidden';
		}
	}

	// get ID field, unique fields, check for unchangeable fields
	$save_old_record = array();
	$unique_fields = array(); // for WHERE operations
	foreach (array_keys($zz['fields']) as $i) {
		if (isset($zz['fields'][$i]['type'])) { // if not set type defaults to 'text' later on
			switch ($zz['fields'][$i]['type']) {
			case 'id':
				$zz_tab[0][0]['id']['field_name'] = $zz['fields'][$i]['field_name'];
				break;
			case 'write_once':
			case 'display':
				$save_old_record[] = $i;
				break;
			}
		}
		if (!empty($zz['fields'][$i]['unique']))
			$unique_fields[$zz['fields'][$i]['field_name']] = true;
		if (!empty($zz['fields'][$i]['field_name']) AND
			!empty($zz_var['zz_fields'][$zz['fields'][$i]['field_name']])) {
				$zz['fields'][$i] = array_merge($zz['fields'][$i], 
					$zz_var['zz_fields'][$zz['fields'][$i]['field_name']]);
			}
	}

//	WHERE, 1st part, with values

	if (!empty($where_condition)) {
		foreach ($where_condition as $field_name => $value) {
			// allows you to set a different (or none at all) table name for WHERE queries
			if (!isset($zz['table_for_where'][$field_name])) 
				$zz['table_for_where'][$field_name] = $zz['table'];
			if (strstr($field_name, ' ') OR strstr($field_name, ';')) {
				unset($where_condition[$field_name]);
				continue;
			}
			$submitted_field_name = $field_name;
			// check if field_name comprises table_name
			if (strstr($field_name, '.')) {
				$field_tab = explode('.', $field_name);
				$table_name = mysql_real_escape_string($field_tab[0]);
				$field_name = mysql_real_escape_string($field_tab[1]);
				unset($field_tab);
			} else {
				$table_name = $zz['table_for_where'][$field_name];
				$field_name = mysql_real_escape_string($field_name);
			}
			$field_reference = ($table_name ? $table_name.'.'.$field_name : $field_name);
			// restrict list view to where, but not to add
			if (empty($_GET['add'][$submitted_field_name])) {
				if (!empty($where_condition[$field_name])
					AND $where_condition[$field_name] == 'NULL') {
					$zz['sql'] = zz_edit_sql($zz['sql'], 'WHERE', 
						'ISNULL('.$field_reference.')');
					continue; // don't use NULL as where variable!
				} else {
					$zz['sql'] = zz_edit_sql($zz['sql'], 'WHERE', 
						$field_reference." = '"
						.mysql_real_escape_string($value)."'");
				}
			}

// hier auch fuer write_once
			$zz_var['where'][$table_name][$field_name] = $value;
			if ($field_name == $zz_tab[0][0]['id']['field_name']) {
				$where_with_unique_id = true;
				$zz_tab[0][0]['id']['value'] = $value;
			} elseif (in_array($field_name, $unique_fields)) {
				$where_with_unique_id = true;
			}
		}
		// in case where is not combined with ID field but UNIQUE field
		// (e. g. identifier with UNIQUE KEY) retrieve value for ID field from database
		if (!($zz_tab[0][0]['id']['value'])) {
			if ($zz_conf['modules']['debug']) {
				zz_debug(__FUNCTION__, $zz_debug_time_this_function, "where_conditions", $zz['sql']);
			}
			$result = mysql_query($zz['sql']);
			if ($result AND mysql_num_rows($result) == 1) {
				$line = mysql_fetch_array($result);
				$zz_tab[0][0]['id']['value'] = $line[$zz_tab[0][0]['id']['field_name']];
//			} else {
//				$zz_error[] = array(
//					'msg_dev' => zz_text('Database error. This database has ambiguous values in ID field.'),
//					'level' => E_USER_ERROR
//				);
//				$zz['output'].= '</div>';
//				return zz_error(); // exit script
			}
			if (!$zz_tab[0][0]['id']['value']) $where_with_unique_id = false;
		}
	}

//
//	Check mode, action, access for record;
//	access for list will be checked later
//

	// internal variables, mode and action
	$zz['mode'] = false;		// mode: what form/view is presented to the user
	$zz['action'] = false;		// action: what database operations are to be done

	// initalize export module
	// might set mode to export
	if (!empty($zz_conf['export'])) zz_export_init($zz_allowed_params);

	// set $zz['mode'], $zz['action'], ['id']['value'] and $zz_conf for access
	$zz = zz_record_access($zz, $zz_conf, $zz_tab, $zz_var, $zz_allowed_params, $where_with_unique_id);

	// mode won't be changed anymore before record operations

	// action won't be changed before record operations
	// (there it will be changed depending on outcome of db operations)
	// so we can set it to $zz_tab
	$zz_tab[0][0]['action'] = $zz['action'];
	
	// check if we are in export mode
	if ($zz_conf['access'] == 'export') {
		$zz['filetype'] = $zz_conf['export_filetypes'][0]; // default filetype for export
		if (!empty($_GET['export'])) { // get filetype for export
			if (in_array($_GET['export'], $zz_conf['export_filetypes']))
				$zz['filetype'] = $_GET['export'];
		} elseif (!empty($_GET['filetype'])) // get filetype for export
			if (in_array($_GET['filetype'], $zz_conf['export_filetypes']))
				$zz['filetype'] = $_GET['filetype'];
	}

	// Turn off hierarchical sorting when using search
	// TODO: implement hierarchical view even when using search
	if (!empty($_GET['q']) AND $zz_conf['search'] AND $zz_conf['show_hierarchy']) {
		$zz_conf['show_hierarchy'] = false;
	}
	
//	Required files

	require_once $zz_conf['dir_inc'].'/editform.inc.php';			// Form
	if ($zz_conf['show_list'])
		require_once $zz_conf['dir_inc'].'/edittab.inc.php';		// Table output with all records
	require_once $zz_conf['dir_inc'].'/editrecord.inc.php';			// update/delete/insert
	require_once $zz_conf['dir_inc'].'/editval.inc.php';			// Basic Validation
	require $zz_conf['dir_inc'].'/text-en.inc.php';					// English text
	if ($zz_conf['additional_text'] AND file_exists($langfile = $zz_conf['lang_dir'].'/text-en.inc.php')) 
		include $langfile; // must not be include_once since $text is cleared beforehands

	if ($zz_conf['modules']['debug']) {
		zz_debug(__FUNCTION__, $zz_debug_time_this_function, "required files included");
	}
	
//	Optional files

	if (isset($zz_conf['language']) && $zz_conf['language'] != 'en') {	// text in other languages
		$langfile = $zz_conf['dir_inc'].'/text-'.$zz_conf['language'].'.inc.php';
		if (file_exists($langfile)) include $langfile;
		else {
			$zz_error[] = array(
				'msg_dev' => sprintf(zz_text('No language file for "%s" found. Using English instead.'), '<strong>'.$zz_conf['language'].'</strong>'),
				'level' => E_USER_NOTICE
			);
		}
		if ($zz_conf['additional_text'] AND file_exists($langfile = $zz_conf['lang_dir'].'/text-'.$zz_conf['language'].'.inc.php')) {
			include $langfile; // must not be include_once since $text is cleared beforehands
		}
	}
	if (!empty($zz_conf['text'][$zz_conf['language']])) {
		$text = array_merge($text, $zz_conf['text'][$zz_conf['language']]);
	}
	// todo: if file exists else lang = en

	if (!function_exists('datum_de')) include_once $zz_conf['dir_inc'].'/numbers.inc.php';
	if (file_exists($zz_conf['dir_inc'].'/forcefilename-'.$zz_conf['character_set'].'.inc.php'))
		include_once $zz_conf['dir_inc'].'/forcefilename-'.$zz_conf['character_set'].'.inc.php';

	if ($zz_conf['modules']['debug']) {
		zz_debug(__FUNCTION__, $zz_debug_time_this_function, "files and database connection ok");
	}

//	Variables

	if ($zz_conf['access'] != 'export') {
		$zz['output'].= '<div id="zzform">'."\n";
		$zz['output'].= zz_error(); // initialise zz_error
	}	

	$zz_conf['heading'] = !isset($zz_conf['heading']) ? zz_form_heading($zz['table']) : $zz_conf['heading'];
	if ($zz_conf['multilang_fieldnames'])
		$zz_conf['heading'] = zz_text($zz_conf['heading']);

	//	Translation module
	//	check whether or not to include default translation subtables
	if ($zz_conf['modules']['translations']) {
		$zz['fields'] = zz_translations_init($zz['table'], $zz['fields']);
		if ($zz_error['error']) {
			if ($zz_conf['access'] != 'export') $zz['output'].= '</div>';
			if ($zz_conf['db_current']) mysql_select_db($zz_conf['db_current']);
			return false; // if an error occured in zz_translations_check_for, return false
		}
	}

	foreach (array_keys($zz['fields']) as $i) {
		// get write once fields so we can base conditions (scope=values) on them
		if (!empty($zz['fields'][$i]['type']) AND $zz['fields'][$i]['type'] == 'write_once' 
			AND ($zz['mode'] != 'add' AND $zz['action'] != 'insert')) { 
			$zz_var['write_once'][$zz['fields'][$i]['field_name']] = '';
		}
	}

// 	WHERE, 2nd part, write_once without values

	// write_once will be checked as well, without values
	// where is more important than write_once, so remove it from array if
	// there is a where equal to write_once
	if (!empty($zz_var['write_once'])) {
		foreach (array_keys($zz_var['write_once']) as $field_name) {
			if (empty($where_condition[$field_name])) {
				$where_condition[$field_name] = '';
				$zz_var['where'][$zz['table']][$field_name] = '';
			} else
				unset($zz_var['write_once'][$field_name]);
		}
	}

	if (!empty($_GET['group']))
		foreach ($zz['fields'] as $index => $field)
			if ((isset($field['display_field']) && $field['display_field'] == $_GET['group'])
				OR (isset($field['field_name']) && $field['field_name'] == $_GET['group'])
			) {
				if (isset($field['order'])) $zz_conf['group'] = $field['order'];
				else $zz_conf['group'] = $_GET['group'];
			}
	
//	process table description zz['fields']

	// if no operations with the record are done, remove zz_fields
	if (!$zz['action'] AND (!$zz['mode'] OR $zz['mode'] == 'list_only'))
		unset($zz_var['zz_fields']);

	// ### variables for main table will be saved in zz_tab[0]
	$zz_tab[0]['table'] = $zz['table'];
	$zz_tab[0]['sql'] = $zz['sql'].(!empty($zz['sqlorder']) ? ' '.$zz['sqlorder'] : '');

//	Add, Update or Delete

	$validation = true;

	if (!empty($_GET['q']) AND $zz_conf['search']) // only if search is allowed and there is something
		$zz['sql'] = zz_search_sql($zz['fields'], $zz['sql'], $zz['table'], $zz_tab[0][0]['id']['field_name']);	// if q modify $zz['sql']: add search query

	if ($zz_conf['modules']['debug']) {
		zz_debug(__FUNCTION__, $zz_debug_time_this_function, "start conditions");
	}

	// Module 'conditions': evaluate conditions
	if (!empty($zz_conf['modules']['conditions']) AND !empty($zz['conditions']))
		$zz_conditions = zz_conditions_record_check($zz, $zz_tab, $zz_var);
	else
		$zz_conditions = array();
	
	// conditions for list view will be set later
	$zz['fields_in_list'] = $zz['fields']; 

	if (!empty($zz_conf['modules']['conditions']) AND !empty($zz_conditions['values']))
		$zz['fields'] = zz_conditions_record_fields($zz['fields'], $zz['conditional_fields'], $zz_conditions['values']);
		
	// check if there are any subtables, any bool-conditions 
	$subqueries = '';
	$j = 1;
	foreach (array_keys($zz['fields']) as $i) {
		if (!empty($zz_conf['modules']['conditions'])) {
			if (!empty($zz['fields'][$i]['conditions'])) {
				$zz['fields'][$i] = zz_conditions_merge($zz['fields'][$i], $zz_conditions['bool'], $zz_tab[0][0]['id']['value']);
			}
			if (!empty($zz['fields'][$i]['not_conditions'])) {
				$zz['fields'][$i] = zz_conditions_merge($zz['fields'][$i], $zz_conditions['bool'], $zz_tab[0][0]['id']['value'], true);
			}
		}
		if (isset($zz['fields'][$i]['type'])) {
			switch ($zz['fields'][$i]['type']) {
			case 'subtable':
				$subqueries[$j] = $i;
				$zz['fields'][$i]['subtable'] = $j;
				if (!isset($zz['fields'][$i]['table_name']))
					$zz['fields'][$i]['table_name'] = $zz['fields'][$i]['table'];
				$j++;
				if (!empty($zz['fields'][$i]['sql_not_unique'])) {
					// must not change record where main record is not directly superior to detail record 
					// - foreign ID would be changed to main record's id
					$zz['fields'][$i]['access'] = 'show';	
					$zz['fields'][$i]['keep_detailrecord_shown'] = true;
				}
				foreach ($zz['fields'][$i]['fields'] as $subfield) {
					if (!empty($subfield['type']) AND $subfield['type'] == 'upload_image') {
						$upload_form = true;
					}
				}
				break;
			case 'upload_image':
				$upload_form = true;
				break;
			}
		}
	}

	// now we have the correct field definitions	
	// set type, title etc. where unset
	zz_fill_out($zz['fields'], $zz_tab[0]['db_name'].'.'.$zz['table']); 

//	Upload

	if (empty($upload_form)) unset($zz_conf['upload']); // values are not needed
	if (in_array('upload', $zz_conf['modules']) && $zz_conf['modules']['upload'])
		if ($zz_conf['upload_MAX_FILE_SIZE'] > ZZ_UPLOAD_INI_MAXFILESIZE) {
			$zz_error[] = array(
				'msg_dev' => 'Value for upload_max_filesize from php.ini is smaller than value which is set in the script. The value from php.ini will be used. To upload bigger files, please adjust your configuration settings.',
				'level' => E_USER_NOTICE
			);
			$zz_conf['upload_MAX_FILE_SIZE'] = ZZ_UPLOAD_INI_MAXFILESIZE;
		}

//	page output
	if (!empty($where_condition)) {
		// make nicer headings
		zz_nice_headings($zz['fields'], $zz_conf, $zz_error, $where_condition);
	}
	$zz_conf['title'] = strip_tags($zz_conf['heading']);
	if ($zz_conf['access'] != 'export') {
		$zz['output'].= "\n".'<h1>'.$zz_conf['heading'].'</h1>'."\n\n";
//		echo '<br>Mode: '.$zz['mode'];
//		echo '<br>Action: '.$zz['action'];
		if ($zz_conf['heading_text'] 
			AND (!$zz_conf['heading_text_hidden_while_editing'] OR $zz['mode'] == 'list_only')) 
			$zz['output'] .= $zz_conf['heading_text'];
		$zz['output'].= zz_error();
		if ($zz_conf['selection'])
			$zz['output'].= "\n".'<h2>'.$zz_conf['selection'].'</h2>'."\n\n";
	}

	// ### variables for main table will be saved in zz_tab[0]
	$zz_tab[0][0]['fields'] = $zz['fields'];
	$zz_tab[0][0]['validation'] = true;
	$zz_tab[0][0]['record'] = false;
	$zz_tab[0][0]['access'] = (!empty($zz['access']) ? $zz['access'] : false);
	
	//	### put each table (if more than one) into one array of its own ###
	zz_get_subqueries($subqueries, $zz, $zz_tab, $zz_conf);
	if ($subqueries && $zz['action'] != 'delete')
		if (isset($_POST['subtables'])) $validation = false;
	
// Upload
	// if there is a directory which has to be renamed, save old name in array
	// do the same if a file might be renamed, deleted ... via upload
	// or if there is a display or write_once field (so that it can be used
	// e. g. for identifiers):
	if (($zz['action'] == 'update' OR $zz['action'] == 'delete')) {
		if (!empty($zz_conf['folder']) OR !empty($upload_form) OR count($save_old_record))
			zz_foldercheck_before($zz_tab);
		if (count($save_old_record) && !empty($zz_tab[0][0]['old_record'])) {
			foreach ($save_old_record as $i) {
				if (!empty($zz_tab[0][0]['old_record'][$zz['fields'][$i]['field_name']])) {
					$_POST[$zz['fields'][$i]['field_name']] = $zz_tab[0][0]['old_record'][$zz['fields'][$i]['field_name']];
				}
			}
		}
	}
	if (!empty($_POST['zz_action'])) {
		$_POST = zz_check_def_vals($_POST, $zz_tab[0][0]['fields'], 
			(!empty($zz_var['where'][$zz_tab[0]['table']]) ? $zz_var['where'][$zz_tab[0]['table']] : ''));
		if (!empty($_FILES)) 
			$_FILES = zz_check_def_files($_FILES);
		// fields with values must still have values
		// TODO TODO
		$zz_tab[0][0]['POST'] = $_POST;
	}

//	Start action
	$zz['formhead'] = false;
	$record_action = false;
	if ($zz['action'] == 'insert' OR $zz['action'] == 'update' OR $zz['action'] == 'delete')
		$record_action = zz_action($zz_tab, $zz_conf, $zz, $validation, $upload_form, $subqueries); // check for validity, insert/update/delete record
	if ($zz_error['error']) {
		if ($zz_conf['access'] != 'export') $zz['output'].= '</div>';
		if ($zz_conf['db_current']) mysql_select_db($zz_conf['db_current']);
		return false; // if an error occured in zz_action, return false
	}

//	Query updated, added or editable record

	if (!$validation) {
		if ($zz['action'] == 'update') $zz['mode'] = 'edit';
		elseif ($zz['action'] == 'insert') $zz['mode'] = 'add';
		zz_get_subqueries($subqueries, $zz, $zz_tab, $zz_conf);
	}

	if ($zz_conf['modules']['debug']) {
		zz_debug(__FUNCTION__, $zz_debug_time_this_function, "subqueries end");
	}

	// Extra GET Parameter
	$keep_query = array();
	$keep_fields = array('where', 'var', 'order', 'group', 'q', 'scope', 'dir', 'referer', 'url', 'nolist', 'filter');
	if ($zz['mode'] == 'add') $keep_fields[] = 'add';
	foreach ($keep_fields AS $key) {
		if (!empty($_GET[$key])) $keep_query[$key] = $_GET[$key];
	}
	// write some query strings differently
	if (isset($_GET['nolist'])) 
		$keep_query['nolist'] = true;
	if ($zz_conf['this_limit'] && $zz_conf['this_limit'] != $zz_conf['limit'])
		$keep_query['limit'] = $zz_conf['this_limit'];

	$zz_var['extraGET'] = http_build_query($keep_query);
	if ($zz_var['extraGET']) 
		$zz_var['extraGET'] = '&amp;'.str_replace('&', '&amp;', $zz_var['extraGET']);

//	Display Updated, Added or Editable Record
	
	// Query for table below record and for value = increment
	// moved to end

	$no_record_form = array('review', 'export', 'list_only');
	
	$form_open = false; // Variable to correctly close form markup in case of error
	if ($zz['mode'] && !in_array($zz['mode'], $no_record_form)) {
	//	mode = add | edit | delete: show form
		if ($zz['mode'] == 'delete' OR $zz['mode'] == 'show') $display_form = 'review';
		else $display_form = 'form';
		if ($zz['mode'] != 'show') {
			$zz['output'].= '<form action="'.$zz_conf['url_self'].$zz_conf['url_self_qs_base'];
			$form_open = true;
			if ($zz_var['extraGET']) $zz['output'].= $zz_var['url_append'].substr($zz_var['extraGET'], 5); // without first &amp;!
			$zz['output'].= '" method="POST"';
			if (!empty($upload_form)) $zz['output'] .= ' enctype="multipart/form-data"';
			$zz['output'].= ' accept-charset="'.$zz_conf['character_set'].'">';
		}
		$zz['formhead'] = zz_text($zz['mode']).' '.zz_text('a_record');
	} elseif ($zz['action']) {	
	//	action = insert update review: show form with new values
		if ($zz['action'] == 'delete') $display_form = false;
		else $display_form = 'review';
		if (!$zz['formhead']) {
			$zz['formhead'] = ucfirst(zz_text($zz['action']).' '.zz_text('failed'));
			$display_form = false;
		}
		if (!empty($zz['no-delete'])) {
			$zz['formhead'] = zz_text('warning').'!';
			foreach ($zz['no-delete'] as $tab) {
				$tab = explode(',', $tab);
				$no_delete_reason = $zz_tab[$tab[0]][$tab[1]]['no-delete'];
				$tmp_error_msg = 
					zz_text('This record could not be deleted because there are details about this record in other records.')
					.' '.$no_delete_reason['text']."\n";
				if (isset($no_delete_reason['fields'])) {
					$tmp_error_msg .= '<ul>'."\n";
					foreach ($no_delete_reason['fields'] as $del_tab) {
						if ($zz_conf['prefix']) { // makes the response look nicer
							if (strtolower(substr($del_tab, 0, strlen($zz_conf['prefix']))) == strtolower($zz_conf['prefix']))
								$del_tab = substr($del_tab, strlen($zz_conf['prefix']));
							else {
								$zz_error[] = array(
									'msg_dev' => sprintf(zz_text('Table prefix is incorrect somehow: %s'), substr($del_tab, 0, strlen($zz_conf['prefix'])))
								);
							}
						}
						$del_tab = ucfirst($del_tab);
						$tmp_error_msg .= '<li>'.$del_tab.'</li>'."\n";
					}
					$tmp_error_msg .= '</ul>'."\n";
				} 
				$zz_error[]['msg'] = $tmp_error_msg;
			}
		}
	} elseif ($zz['mode'] == 'review') {
		$display_form = 'review';
		$zz['formhead'] = zz_text('show_record');
	} else
		$display_form = false;
	
	if ($zz_conf['modules']['debug']) {
		zz_debug(__FUNCTION__, $zz_debug_time_this_function, "database operations end");
	}

	// requery record
	foreach (array_keys($zz_tab) as $i)
		foreach (array_keys($zz_tab[$i]) as $k)
			if (is_numeric($k)) {
				zz_requery_record($zz_tab[$i], $k, $validation, $zz['mode']);
			}

	if ($zz_error['error']) {
		if ($form_open) $zz['output'] .= '</form>';
		if ($zz_conf['access'] != 'export') $zz['output'].= '</div>';
		if ($zz_conf['db_current']) mysql_select_db($zz_conf['db_current']);
		return false;
	}
	if (!empty($zz_error['validation']['msg']) AND is_array($zz_error['validation']['msg'])) {
		// user error message, visible to everyone
		// line breaks \n important for mailing errors
		$this_error['msg'] = '<p>'.zz_text('Following_errors_occured').': </p>'."\n".'<ul><li>'
			.implode(".</li>\n<li>", $zz_error['validation']['msg']).'.</li></ul>';
		// if we got wrong values entered, put this into a developer message
		if (!empty($zz_error['validation']['incorrect_values'])) {
			foreach ($zz_error['validation']['incorrect_values'] as $incorrect_value) {
				$this_dev_msg[] = zz_text('Field name').': '.$incorrect_value['field_name']
					.' / '.$incorrect_value['msg'];
			}
			$this_error['msg_dev'] = "\n\n".implode("\n", $this_dev_msg);
		}
		$zz_error[] = $this_error;
		unset($this_error);
	}
	unset ($zz_error['validation']);
	
	if (!empty($zz_var['where'][$zz['table']])) {
		foreach ($zz_var['where'][$zz['table']] as $field_name => $value)
		if (!$value) {
			if (!empty($zz_tab[0][0]['record'][$field_name]))
				$zz_var['where'][$zz['table']][$field_name] = $zz_tab[0][0]['record'][$field_name];
		}
	}
	
	// requery record if successful, 
	if (($zz['mode'] == 'edit' OR $zz['mode'] == 'delete' OR $zz['mode'] == 'review') AND !$zz_tab[0][0]['record']) {
		$zz['formhead'] = '<span class="error">'.zz_text('There is no record under this ID:').' '.htmlspecialchars($zz_tab[0][0]['id']['value']).'</span>';	
		$display_form = false;
	}

	// output form if neccessary
	$zz['output'] .= zz_display_records($zz, $zz_tab, $zz_conf, $display_form, $zz_var, $zz_conditions);

	if ($zz['mode'] && !in_array($zz['mode'], $no_record_form) && $zz['mode'] != 'show')
		$zz['output'].= "</form>\n";
	// filter
	if (!empty($zz_conf['filter']) AND $zz_conf['access'] != 'export'
		AND in_array($zz_conf['filter_position'], array('top', 'both')))
		$zz['output'] .= zz_filter_selection($zz_conf['filter']);
	if ($zz['mode'] != 'add' && $zz_conf['add_link'] && !is_array($zz_conf['add'])
		&& $zz_conf['access'] != 'export')
		$zz['output'].= '<p class="add-new"><a accesskey="n" href="'.$zz_conf['url_self']
			.$zz_conf['url_self_qs_base'].$zz_var['url_append'].'mode=add'
			.$zz_var['extraGET'].'">'.zz_text('Add new record').'</a></p>'."\n";
	if ($zz_conf['backlink']) {
		if (!empty($zz_conf['dynamic_referer']))
			$zz['output'].= '<p id="back-overview"><a href="'
				.zz_makepath($zz_conf['dynamic_referer'], $zz_tab, 'new', 'local')
				.'">'.zz_text('back-to-overview').'</a></p>'."\n";
		elseif ($zz_conf['referer'])
			$zz['output'].= '<p id="back-overview"><a href="'.$zz_conf['referer_esc'].'">'.zz_text('back-to-overview').'</a></p>'."\n";
	}
	
	if ($zz_conf['show_list']) {
		zz_display_table($zz, $zz_conf, $zz_error, $zz_var, $zz_tab[0][0]['id']['field_name'], $zz_conditions); 
		// shows table with all records (limited by zz_conf['limit'])
		// and add/nav if limit/search buttons
	}
	if ($zz_error['error']) {
		if ($zz_conf['access'] != 'export') $zz['output'].= '</div>';
		if ($zz_conf['db_current']) mysql_select_db($zz_conf['db_current']);
		return false; // critical error: exit;
	}


	if ($zz_conf['modules']['debug']) {
		zz_debug(__FUNCTION__, $zz_debug_time_this_function, "finished");
		if ($zz_conf['debug']) {
			$zz['output'] .= '<div class="debug">'.zz_debug_htmlout($zz_debug).'</div>'."\n";
		}
	}
	// Redirect, if wanted.
	if ($zz['result']) {
		// debug time only if there's a result and before leaving the page
		if ($zz_conf['modules']['debug'] AND $zz_conf['debug_time']) {
			$zz_error[] = array(
				'msg_dev' => '[DEBUG] time: '.implode(' ', $zz_debug['time']),
				'level' => E_USER_NOTICE
			);
			zz_error();
		}
		if (!empty($zz_conf['redirect'][$zz['result']])) {
			if (substr($zz_conf['redirect'][$zz['result']], 0, 1) == '/') {
				$scheme = ((isset($_SERVER['HTTPS']) AND $_SERVER['HTTPS'] == "on") ? 'https' : 'http');
				$zz_conf['redirect'][$zz['result']] = $scheme.'://'.$_SERVER['SERVER_NAME'].$zz_conf['redirect'][$zz['result']];
			}
			header('Location: '.$zz_conf['redirect'][$zz['result']]);
			exit;
		}
	}
	if ($zz_conf['access'] != 'export') {
		if ($zz_conf['footer_text']) $zz['output'].= $zz_conf['footer_text'];
		 $zz['output'].= '</div>';
	}
	if ($zz_conf['show_output']) echo $zz['output'];
//	if ($record_action) {
//		$scheme = ((isset($_SERVER['HTTPS']) AND $_SERVER['HTTPS'] == "on") ? 'https' : 'http');
//		übergabe via SESSION, so dass bestätiger Datensatz angezeigt wird.
//		header('Location: '.$scheme.'://'.$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']); // Parameter, die bestätigten Record anzeigen
//	}
	// return to old database
	if ($zz_conf['db_current']) mysql_select_db($zz_conf['db_current']);
}

function zzform_all($glob_vals = false) {
//	Die folgenden globalen Definitionen der Variablen sind nur noetig, wenn man wie
//	hier die darauffolgenden vier Zeilen in einer Funktion zusammenfassen will
	global $zz;			// Table description
	global $zz_conf;	// Config variables
	global $zz_tab;		// Table values, generated by zzform()
	global $zz_page;	// Page (Layout) variables
	global $zz_setting;	// Settings
	if ($glob_vals)		// Further variables, may be set by user
		if (is_array($glob_vals))
			foreach ($glob_vals as $glob_val)
				global $$glob_val;
		else
			global $$glob_vals;
	$zz_conf['show_output'] = false; // do not show output as it will be included after page head
	
//	Zusammenbasteln der Seite
	zzform();					// Funktion aufrufen
	if ($zz['mode'] == 'export') {
		foreach ($zz['headers'] as $index) {
			foreach ($index as $bool => $header) {
				header($header, $bool);
			}
		}
		echo $zz['output'];			// Output der Funktion ausgeben
	} else {
		if (empty($zz_page['title'])) $zz_page['title'] = $zz_conf['title'];
		include $zz_page['head'];	// Seitenkopf ausgeben, teilw. mit Variablen aus Funktion
		echo $zz['output'];			// Output der Funktion ausgeben
		include $zz_page['foot'];	// Seitenfuss ausgeben
	}
}


function zz_initialize(&$zz_allowed_params, &$zz_var) {
	global $zz_conf;
	// Always get debug time, there's no debug module yet
	$zz_debug_time_this_function = microtime_float();
	global $zz_error;

	//	allowed parameters
	$zz_allowed_params['mode'] = array('edit', 'delete', 'show', 'add', 'review', 'list_only');
	$zz_allowed_params['action'] = array('insert', 'delete', 'update'); // review is for internal use only
	
	//	Core defaults and functions
	$zz_default['character_set']	= 'utf-8';					// character set
	$zz_default['dir_ext']			= $zz_conf['dir'].'/ext';	// directory for extensions
	$zz_default['dir_custom']		= $zz_conf['dir'].'/local';
	$zz_default['dir_inc']			= $zz_conf['dir'].'/inc';
	$zz_default['error_mail_level']	= array('error', 'warning', 'notice');
	$zz_default['ext_modules']		= array('markdown', 'textile');
	foreach (array_keys($zz_default) as $key)					// create conf from defaults
		if (!isset($zz_conf[$key])) 
			$zz_conf[$key] = $zz_default[$key];
	// shorthand values
	if (!is_array($zz_conf['error_mail_level'])) {
		if ($zz_conf['error_mail_level'] == 'error') $zz_conf['error_mail_level'] = array('error');
		elseif ($zz_conf['error_mail_level'] == 'warning') $zz_conf['error_mail_level'] = array('error', 'warning');
		elseif ($zz_conf['error_mail_level'] == 'notice') $zz_conf['error_mail_level'] = array('error', 'warning', 'notice');
	}
	require_once $zz_conf['dir_inc'].'/editfunc.inc.php';		// include core functions


//	Modules

	// todo: include modules geo and upload only if corresponding fields are defined, 
	// see $upload_form as a way how to do that.
	// debug module must come first because of debugging reasons!
	$int_modules = array('debug', 'geo', 'validate', 'export', 'compatibility', 'upload', 
		'conditions', 'translations');
	$int_modules = zz_add_modules($int_modules, $zz_conf['dir_inc'], $zz_conf);
	$zz_conf['modules'] = $int_modules['modules'];
	$ext_modules = zz_add_modules($zz_conf['ext_modules'], $zz_conf['dir_ext'], $zz_conf);
	foreach ($int_modules['vars'] as $index => $var) {			// import variables from internal modules
		if (is_array($var)) {
			$$index = zz_array_merge($$index, $var);
		}
	}
	if ($zz_error['error']) return false;		// stop if there were errors while adding modules

	$zz_conf['ext_modules'] = $ext_modules['modules'];
		
	$zz_conf['selection'] 			= false;
	$zz_default['group']			= false;
	$zz_conf['group_field_no']		= false;

	$zz_default['action_dir']		= $zz_conf['dir_custom'];	// directory for included scripts after action has been taken
	$zz_default['lang_dir']			= $zz_conf['dir_custom'];	// directory for additional text

	$zz_default['access']			= '';		// nothing, does not need to be set, might be set individually
	$zz_default['add']				= true;		// add or do not add data.
	$zz_default['additional_text']	= false;
	$zz_default['backlink']			= true;		// show back-to-overview link
	$zz_default['delete']			= false;	// show Action: Delete
	$zz_default['details']			= false;	// column details; links to detail records with foreign key
	$zz_default['details_base']		= false;
	$zz_default['details_referer']	= true;		// add referer to details link
	$zz_default['details_target']	= false;	// target-window for details link
	$zz_default['do_validation']	= true;		// left over from old edit.inc, for backwards compatiblity
	$zz_default['edit']				= true;		// show Action: Edit
	$zz_default['error_handling']		= 'output';
	$zz_default['error_log']['error']	= ini_get('error_log');
	$zz_default['error_log']['notice']	= ini_get('error_log');
	$zz_default['error_log']['warning']	= ini_get('error_log');
	$zz_default['error_mail_from']		= false;
	$zz_default['error_mail_to']		= false;
	$zz_default['log_errors_max_len'] 	= ini_get('log_errors_max_len');
	$zz_default['log_errors'] 			= ini_get('log_errors');

	$zz_default['export']				= false;
	$zz_default['filter_position'] 		= 'top';
	$zz_default['filter'] 				= array();
	$zz_default['footer_text']			= false;		// text at the end of all
	$zz_default['heading_text'] 		= '';
	$zz_default['heading_text_hidden_while_editing'] 	= false;
	$zz_default['limit']				= false;	// only n records are shown at once
	$zz_default['limit_show_range'] 	= 800;		// range in which links to records around current selection will be shown
	$zz_default['list_display']			= 'table';
	$zz_default['logging'] 				= false;	//	if logging should occur, turned off by default 
	$zz_default['logging_table'] 		= '_logging';	// name of table where INSERT, DELETE and UPDATE actions will be logged
	$zz_default['max_detail_records']	= 20;		// max 20 detail records, might be expanded later on
	$zz_default['max_select_val_len']	= 60;		// maximum length of values in select
	$zz_default['max_select'] 			= 60;		// maximum entries in select/option, if bigger than sub-select
	$zz_default['min_detail_records']	= 0;		// min 0 detail records, might be expanded later on
	$zz_default['multi'] 				= false;		// zzform_multi
	$zz_default['multilang_fieldnames'] = false;	// translate fieldnames via zz_text($fieldname)
	$zz_default['prefix'] 				= false;	//	prefix for ALL tables like zz_
	$zz_default['project']				= $_SERVER['SERVER_NAME'];
	$zz_default['redirect']['successful_delete'] = false;	// redirect to diff. page after delete
	$zz_default['redirect']['successful_insert'] = false;	// redirect to diff. page after insert
	$zz_default['redirect']['successful_update'] = false;	// redirect to diff. page after update
	$zz_default['relations_table'] 		= '_relations';	//	name of relations table for referential integrity
	$zz_default['search'] 				= false;	// search for records possible or not
	$zz_default['select_multiple_records'] = false;
	$zz_default['show_hierarchy']	= false;
	$zz_default['show_list_while_edit'] = true;	
	$zz_default['show_list']		= true;		// display list of records in database				
	$zz_default['show_output']		= true;		// ECHO output or keep it in $zz['output']
	$zz_default['tfoot']			= false;  	// shows table foot, e. g. for sums of individual values
	$zz_default['this_limit']		= false;	//	internal value, current range which records are shown
	$zz_default['user']				= '';		//	username
	$zz_default['view']				= false;	// 	show Action: View
	$zz_default['password_encryption'] = 'md5';
	
	foreach (array_keys($zz_default) as $key)
		if (!isset($zz_conf[$key])) $zz_conf[$key] = $zz_default[$key];

	// set default limit in case 'show_hierarchy' is used because hierarchies need more memory
	if (!$zz_conf['limit'] AND $zz_conf['show_hierarchy']) $zz_conf['limit'] = 40;

	$zz_var['url_append'] = '?'; // normal situation: there is no query string in the base url, so add query string starting ?
	$my_uri = parse_url('http://www.example.org'.$_SERVER['REQUEST_URI']);
	$zz_conf['url_self_qs_base'] = ''; // no base query string which belongs url_self
	// get own URI
	if (empty($zz_conf['url_self'])) {
		$zz_conf['url_self'] = $my_uri['path'];
		$zz_conf['url_self_qs_zzform'] = (!empty($my_uri['query']) ? '?'.$my_uri['query'] : ''); // zzform query string
	} else {
		// it's possible to use url_self without http://hostname, so check for that
		$examplebase = (substr($zz_conf['url_self'], 0, 1) == '/' ? 'http://www.example.org' : '');
		$base_uri = parse_url($examplebase.$zz_conf['url_self']);
		if ($examplebase) {
			$zz_conf['url_self'] = $base_uri['path'];
		} else {
			$zz_conf['url_self'] = $base_uri['scheme'].'://'.$base_uri['host'].$base_uri['path'];
		}
		if (!empty($base_uri['query'])) {
			$zz_conf['url_self_qs_base'] = '?'.$base_uri['query']; // no base query string which belongs url_self
			$zz_var['url_append'] ='&amp;';
		}
		if (!empty($my_uri['query']) AND !empty($base_uri['query'])) {
			parse_str($my_uri['query'], $my_uri_query);
			parse_str($base_uri['query'], $base_uri_query);
			foreach ($my_uri_query AS $key => $value) {
				if (!empty($base_uri_query[$key]) AND $base_uri_query[$key] == $value) {
					unset($my_uri_query[$key]);
				}
			}
			unset($base_uri_query);
			$zz_conf['url_self_qs_zzform'] = http_build_query($my_uri_query);
			if ($zz_conf['url_self_qs_zzform']) $zz_conf['url_self_qs_zzform'] = '&'.$zz_conf['url_self_qs_zzform'];
		} elseif (!empty($my_uri['query']))
			$zz_conf['url_self_qs_zzform'] = '&'.$my_uri['query'];
		else
			$zz_conf['url_self_qs_zzform'] = '';
	}
	unset($my_uri);

	// get LIMIT from URI
	if (!$zz_conf['this_limit'] && $zz_conf['limit']) 
		$zz_conf['this_limit'] = $zz_conf['limit'];
	if (isset($_GET['limit']) && is_numeric($_GET['limit']))	
		$zz_conf['this_limit'] = (int) $_GET['limit'];
	
	// don't show list in case 'nolist' parameter is set
	if (isset($_GET['nolist'])) $zz_conf['show_list'] = false;

	// get referer // TODO: add support for SESSIONs as well
	if (!isset($zz_conf['referer'])) {
		$zz_conf['referer'] = false;
		if (isset($_GET['referer'])) $zz_conf['referer'] = $_GET['referer'];
		if (isset($_POST['referer'])) $zz_conf['referer'] = $_POST['referer'];
	} elseif (isset($_POST['referer']))
		$zz_conf['referer'] = $_POST['referer'];
	elseif (isset($_SERVER['HTTP_REFERER']))
		$zz_conf['referer'] = $_SERVER['HTTP_REFERER'];
	$zz_conf['referer_esc'] = str_replace('&', '&amp;', $zz_conf['referer']);

	//	URL parameter
	if (get_magic_quotes_gpc()) { // sometimes unwanted standard config
		$_POST = magic_quotes_strip($_POST);
		$_GET = magic_quotes_strip($_GET);
		$_FILES = magic_quotes_strip($_FILES);
		// _COOKIE and _REQUEST are not being used
	}

	if ($zz_conf['modules']['debug']) zz_debug(__FUNCTION__, $zz_debug_time_this_function);
}

/** call zzform() once or multiple times without user interaction 
 * 
 * @param $definition_file(string) - script filename
 * @param $values(array) - values sent to script (instead of $_GET, $_POST and $_FILES)
 * @param $type(string) - what to do
 * @author Gustaf Mossakowski <gustaf@koenige.org>
 */
function zzform_multi($definition_file, $values, $type, $params = false) {
	// unset all variables that are not needed
	// important because there may be multiple zzform calls
	global $zz_conf;
	global $zz_setting;
	global $zz_saved;

	// Allowed:
	$allowed_types = array('csv', 'xml', 'files', 'record');
	if (!in_array($type, $allowed_types)) {
		echo 'Illegal type set for function zzform_multi(): '.htmlspecialchars($type);
		return false;
	}
	
	// TODO: $glob_vals
	
	unset($_GET);
	unset($_POST);
	unset($_FILES);

	switch ($type) {
	case 'record':  // one operation only
		global $zz;			// Table description
		$zz = array();
		// TODO: so far, we have no support for 'values' for subrecords
		if (!empty($zz_conf['zzform_calls']))
			$zz_conf = $zz_saved['conf'];	// get clean $zz_conf without changes from different zzform calls or included scripts
		$zz_conf['show_output'] = false; // do not show output as it will be included after page head
		$zz_conf['show_list'] = false; // no output, so list view is not neccessary
		$zz_conf['multi'] = true;		// so we know the operation mode for other scripts
		if (!empty($values['GET'])) $_GET = $values['GET'];
		if (!empty($values['POST'])) $_POST = $values['POST'];
		if (!empty($values['FILES'])) $_FILES = $values['FILES'];
		else $_FILES = '';
		require $zz_conf['form_scripts'].'/'.$definition_file.'.php';
		zzform();
		break;
	case 'files':
		require_once $zz_conf['dir_inc'].'/editfunc.inc.php';
		require_once $zz_conf['dir_inc'].'/import.inc.php';
		require_once $zz_conf['dir_inc'].'/forcefilename-'.$zz_conf['character_set'].'.inc.php';
		$zz['output'] = zz_import_files($definition_file, $values, $params);
		return $zz['output'];
	}
	
	// create new $_GET, $_POST and $_FILES from $values as needed
//	$actions = array();	// for each call, create one action


//	foreach ($actions as $action) {
//		$zz_conf = $global_zz_conf;	// get clean $zz_conf without changes from different zzform calls or included scripts
//		zzform();					// Funktion aufrufen
		
		// on success: remove entry in csv file
		// on success: delete files, move files ...
		// on failure: output record, output error ?
//	}
	// TODO: export, might go into extra file?

	// what to return:
	// array whith all record_ids that were inserted, sorted by operation (so to include subrecords)
}

function microtime_float() {
    list($usec, $sec) = explode(" ", microtime());
    return ((float)$usec + (float)$sec);
}

?>